### ISSUE TITLE
IDE: overlapping text in the IDE

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#53] opened 2018-07-25 13:35 UTC
**Describe the bug**
Overlapping text in the IDE.

**To Reproduce**
Edit a file in the IDE.

**Expected behavior**
The text should not overlap and should render as expected.

**Screenshots**
Video: https://awau.moe/52c8ae.mp4
Screenshot:
![Screenshot](https://awau.moe/99d86f.png)

Screenshot shows overlapping of dots (line 7 + 19) and misplacement of text (indentation using 4 spaces looks like indented with 2 spaces, the two dots visualizing the other two spaces placed behind the following text)

Video shows the movement through whitespace

**Desktop (please complete the following information):**
Browser: Google Chrome 67.0.3396.99 and qutebrowser 1.3.0
OS: Windows 10 Home Insider Preview, Build 17692.re_prerelease_flt.180625-1624 (64-Bit)

**Additional context**
Reported via Zendesk.

**Comment by foresthoffman** [comment] 2018-07-25 15:40
Duplicate of https://github.com/codercom/bugs/issues/45

**Closed** 2018-07-25 15:41 UTC
Labels: duplicate
