### ISSUE TITLE
Bug/Feature: need "resend verification code"

### ISSUE THREAD

**Issue by jhalek90** [codercom/bugs#47] opened 2018-07-25 00:43 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by foresthoffman** [comment] 2018-07-25 17:43
Closing as duplicate of #48

**Closed by foresthoffman** 2018-07-25 17:43 UTC
