### ISSUE TITLE
Incorrect Last Opened Date

### ISSUE THREAD

**Issue by zackerysmith** [codercom/bugs#112] opened 2018-08-11 13:28 UTC
**Describe the bug**
The last opened date is incorrect date in the Dashboard.

**To Reproduce**
1. Create a project
2. Navigate to the Dashboard
3. The "Last Opened" Date is "Mon Jan 01 0001"

**Expected behavior**
The correct "Last Opened" Date should be correct date.

**Screenshots**
![image](https://user-images.githubusercontent.com/30194321/43992172-8813cd94-9d98-11e8-8b3c-1f09eb4c1fce.png)

**Comment by deansheather** [comment] 2018-08-11 13:31
Duplicate of #23. Thanks for reporting, though! :smiley:

**Closed by deansheather** 2018-08-11 13:31 UTC
Labels: bug, duplicate, tracking, visual

**Comment by zackerysmith** [comment] 2018-08-11 13:55
Happy to help!
You guys are doing awesome !
