### ISSUE TITLE
IDE: "Create Project" button breaks after changing between tabs in dashboard

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#52] opened 2018-07-25 12:04 UTC
**Describe the bug**
If you change from the "Dashboard" tab to the "Control Panel" tab and back, the "Create Project" button appears to be disabled.

**To Reproduce**
Steps outlined above.

**Expected behavior**

**Screenshots**
n/a

**Desktop (please complete the following information):**
OS: Win 7
Browser: Google Chrome

**Additional context**
Reported via Zendesk.

**Comment by foresthoffman** [comment] 2018-07-25 15:58
I wasn't able to recreate this issue on Mac OS using the latest version of Google Chrome.

**Comment by T0TProduction** [comment] 2018-07-25 21:43
![image](https://user-images.githubusercontent.com/18548570/43229231-637cb8f6-9064-11e8-8a85-c01314de096e.png)
this is what happened to me, I think I did the steps you mentioned (by accident though, wanted to report this and found this post)

**Comment by nol166** [comment] 2018-07-26 19:04
I tested this with browserstack (windows 7, chrome 67) and wasn't able to replicate. I am wondering if it was some weirdness with one of the browser extensions?

**Comment by foresthoffman** [comment] 2018-07-26 19:06
@T0TProduction, thank you for reporting on this. Could you please attempt to reproduce this with your chrome extensions disabled? Please be sure that you have the most recent version of Chrome as well (67.0).

**Comment by foresthoffman** [comment] 2018-07-26 19:15
I'm closing this, as we can't reproduce it currently.

**Closed by foresthoffman** 2018-07-26 19:15 UTC
Labels: invalid
