### ISSUE TITLE
Import folders into project

### ISSUE THREAD

**Issue by mfduar8766** [codercom/bugs#152] opened 2018-08-25 22:30 UTC
The IDE is great, however, I would like a feature where we can upload our projects from our own machine into the virtual IDE that way we don't have to start from scratch. I guess I could git clone a project, but also having the option of uploading an existing one is nice.

**Comment by ammario** [comment] 2018-08-25 22:31
We're working on this right now :+1:

**Comment by NGTmeaty** [comment] 2018-08-25 22:32
Duplicate of #24 on codercom/features?

**Comment by ammario** [comment] 2018-08-25 22:34
I believe so. @mfduar8766 could you confirm that you're looking for the ability to drag and drop files?

**Comment by GeekMustHave** [comment] 2018-08-28 00:56
Just a comment here.  I think having the ability to drag and drop files from the local filesystem would be helpful.  Also being able just to paste text from the clipboard into an edit window would be a big step forward.

**Closed** 2018-09-25 21:04 UTC
