### ISSUE TITLE
Terminal output is static and isn't scrollable

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#165] opened 2018-08-27 21:02 UTC
Aug 27, 2018 at 4:00:49 PM
**What Happened**
Terminal window output is fixed and can't be scrolled.

**Steps to Reproduce**

1. Open terminal
2. Type `npm -l`
3. Attempt to scroll up

**Specs**

1. Operating System: MacOS
2. Browser and Version: Chrome 68
3. Issue present in incognito mode: [yes/no] Y

**Suggested Fix**
Make terminal output scrollable

**Comment by deansheather** [comment] 2018-09-02 09:47
Duplicate of #62.

**Closed by deansheather** 2018-09-02 09:47 UTC
Labels: bug, tracking
