### ISSUE TITLE
IDE: changing keyboard shortcuts doesn't work

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#226] opened 2018-11-06 13:15 UTC
**Describe the bug**
When you change a keyboard shortcut, the keyboard shortcut buffer freezes.

**To Reproduce**
1. Open the IDE
2. Open the Keyboard Shortcuts preferences
3. Change the save shortcut to something like Ctrl+Numpad1
4. Notice how it freezes for a second
5. Notice how it doesn't write the changes

**Expected behavior**
The keyboard shortcuts menu should work properly.

**Screenshots**
n/a

**Desktop:**
 - OS: Linux
 - Browser: Chromium
 - Version: 69.0.3497.100 (Developer Build) (64-bit)

**Additional context**
Originally reported via Discord.

**Comment by jaymeramsay** [comment] 2018-11-06 23:08
I'm currently unable to reproduce this with Linux and Mac.

**Comment by kylecarbs** [comment] 2018-11-08 00:04
Should be fixed :confetti_ball:

**Closed by kylecarbs** 2018-11-08 00:04 UTC
