### ISSUE TITLE
Creating project with the same name as deleted project restores files

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#63] opened 2018-07-26 15:56 UTC
Jul 26, 2018 at 10:52:01 AM
### What happened
User created a project with title `temp`, then deleted that project and created another project with the same name. The files from the initial project were not deleted. Effectively his old project was restored

### Suggested fix
Ensure that files are unlinked when the project is deleted

### Steps to reproduce
1. From the projects page create a project
2. Open the project in IDE
3. Create `file.js`
4. Go back to dashboard
5. Delete project
6. Create another project with the same name
7. Launch project in IDE
8. Notice that the file is still present

**Comment by pokemonlover1234** [comment] 2018-08-02 11:53
@nol (pinging cause behavior changed). Seems now, while the files still seem to persist, after deleting and recreating the project in the dashboard, upon first load of the recreated project, the IDE fails to load with a Clide error stating that it didn't get a mount response, however on every subsequent reload it successfully loads. Behavior reported via Discord and reproduced by me twice (with same project, so behavior happens on every recreate).

**Comment by nol166** [comment] 2018-08-02 15:06
@pokemonlover1234 after you reload after the clide error and it finally lets you into the IDE, are your old files still present?

**Comment by pokemonlover1234** [comment] 2018-08-02 15:33
Yes

**Comment by ammario** [comment] 2018-08-12 03:31
Duplicate of #44

**Closed by ammario** 2018-08-12 03:31 UTC
Labels: bug, tracking
