### ISSUE TITLE
Theming: Same theme looks different coming from other themes

### ISSUE THREAD

**Issue by TheEvilSocks** [codercom/bugs#39] opened 2018-07-24 13:37 UTC
**Describe the bug**
When switching around themes, coming from themes may look different when switching from other themes. (No idea how to explain, just look at the YouTube video)

**To Reproduce**
1. Open theming menu
2. Switch to a theme.
3. Switch to another theme
4. Switch to theme from step 2
5. Theme in step 4 will look different from step 2

**Expected behavior**
The same theme should always look the same.

**Screenshots**
https://www.youtube.com/watch?v=4S1fccjB4DA

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 bionic
 - Browser: FireFox 
 - Version 61.0.1 (64-Bit)

**Comment by jhalek90** [comment] 2018-07-24 14:54
Thanks for the bug report. We have identified the cause, and are working on rolling out a fix soon.

In the mean time, if you refresh the IDE page, it should properly display the theme

**Comment by kylecarbs** [comment] 2018-08-13 03:56
Should be fixed :confetti_ball:

**Comment by pokemonlover1234** [comment] 2018-09-13 17:45
A user in Discord reported experiencing this issue again

**Comment by coadler** [comment] 2018-09-13 17:49
![bug](https://cdn.discordapp.com/attachments/467356520711979018/489853241127862272/theme_picker_bug.gif) @kylecarbs

**Closed** 2018-11-06 15:49 UTC
