### ISSUE TITLE
npm install ngrok -g fails

### ISSUE THREAD

**Issue by moflo** [codercom/bugs#240] opened 2018-11-10 03:07 UTC
**Describe the bug**
ngrok npm wrapper fails to install
 
**To Reproduce**
`npm install ngrok -g`

**Expected behavior**

**Screenshots**
```
/coder/volume/node/10.5.0/bin/ngrok -> /coder/volume/node/10.5.0/lib/node_modules/ngrok/bin/ngrok

> ngrok@3.1.0 postinstall /coder/volume/node/10.5.0/lib/node_modules/ngrok
> node ./postinstall.js

sh: 1: node: Permission denied
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngrok@3.1.0 postinstall: `node ./postinstall.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ngrok@3.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**Additional context**
Work around is to install `ngrok` binaries directly.

**Comment by deansheather** [comment] 2018-11-10 06:05
Duplicate of #211 (Npm install failing with "Permission denied").

**Closed by deansheather** 2018-11-10 06:05 UTC
Labels: bug, duplicate, tracking
