### ISSUE TITLE
Modal for container offline is not working

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#183] opened 2018-08-31 15:39 UTC
Aug 31, 2018 at 10:34:01 AM
**What Happened**
A user had IDE open overnight when his container had turned off. He noticed that there was no notification that the container went offline. This should be added.

**Steps to Reproduce**

1. Open two tabs with coder
2. In tab 1, open project 
3. In tab 2, turn off container
4. Observe behavior in IDE

**Specs**

1. Operating System: MacOS
2. Browser and Version: Chrome 68
3. Issue present in incognito mode: [yes/no] Y

**Suggested Fix**
Add disconnect modal

**Comment by coadler** [comment] 2018-08-31 15:53
Duplicate of #102

**Closed** 2018-09-03 01:40 UTC
Labels: bug, tracking
