### ISSUE TITLE
F2 shortcut for renaming items does not behave correctly

### ISSUE THREAD

**Issue by afischer12** [codercom/bugs#65] opened 2018-07-26 17:10 UTC
**Describe the bug**
F2 Shortcut for renaming items only works if left mouse button is actively held down and exits if mouse is released.

**To Reproduce**
1. Open the Project's IDE
2. Go to a file/folder you wish to rename
3. Click and hold on a file/folder and hit F2
4. Release F2

**Expected behavior**
Just having to select and not hold down the mouse button on a file/folder in order for F2 to work and not having to hold the mouse button down the whole time.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Version 67.0.3396.99 (Official Build) (64-bit)]

**Comment by afischer12** [comment] 2018-07-26 17:12
Correction; I just found the shortcuts menu, and found the F2 option, however this only works if the mouse is actively pressed down on the file and the rename field exits if the mouse is released. I'll update the bug report accordingly.

**Comment by nol166** [comment] 2018-07-26 18:19
Thanks for posting this. I made our engineering team aware of the issue.

**Comment by pokemonlover1234** [comment] 2018-07-26 20:03
F2 issue seems to be fixed. Also #8 being fixed now allows for renaming using right click. Wasn't aware that was an issue.

**Comment by jaymeramsay** [comment] 2018-08-24 22:01
I've reproduced this issue on Windows 10 and Chrome.

**Closed** 2018-11-06 16:06 UTC
Labels: bug, tracking
