### ISSUE TITLE
my container uses python 3.5 with vs code - how do I get python 3.7 in the vs code environment

### ISSUE THREAD

**Issue by rholland** [codercom/bugs#330] opened 2019-02-21 21:35 UTC
The Ubuntu version of the container is 16.04 (Xenia).  In terminal mode the python command responds with an error.  The python3 command opens python 3.5.    I cannot update the apt repository in the terminal in order to update python.

I need python 3.6 or 3.7 in the vs code environment

Thanks.

**Comment by foresthoffman** [comment] 2019-02-21 22:10
Hi, @rholland, If you wish to use a different version of Python than those you've mounted, you'll need to ensure that both Python versions have been unmounted via the Command Palette. Then, any Python binaries that you install from a package manager, such as apt, will take precedence. What you're seeing is the Coder binaries are being discovered first, since the `/coder/bin` directory comes before all others in your `PATH` (by default).

**Comment by foresthoffman** [comment] 2019-02-21 22:12
Going to close this, as this is not a bug. Further assistance can be provided in response to a support ticket submitted while logged into Coder.com.

Thanks!

**Closed by foresthoffman** 2019-02-21 22:12 UTC

**Comment by rholland** [comment] 2019-02-21 23:28
I am not sure what you are saying. I think the basic issue is vscode runs on an old Ubuntu (16.04) platform and the fact that the container does not allow for repository extensions.  The command pallet does not allow python unmounting.  vscode uses python from the underlying os. and the os locks down changes to the repository needed to get python 3.6 for the older os.  Also I noticed vscode is an older version which means  the python extension it offers is from October.  It was updated several times since then.  

I will try to pursue this through support.
